/**
 * Tests for scripts/generate-colors.js
 *
 * Verifies color generation from YAML config.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { loadConfig, generateJS, generateSH } = require('../../scripts/generate-colors');

describe('generate-colors', () => {
  describe('loadConfig', () => {
    it('loads colors.yaml configuration', () => {
      const config = loadConfig();
      expect(config).toBeDefined();
      expect(config.brand).toBeDefined();
      expect(config.brand.hex).toBe('#e8683a');
    });

    it('has modifiers section', () => {
      const config = loadConfig();
      expect(config.modifiers).toBeDefined();
      expect(config.modifiers.reset).toBe('0');
      expect(config.modifiers.bold).toBe('1');
      expect(config.modifiers.dim).toBe('2');
    });

    it('has standard colors section', () => {
      const config = loadConfig();
      expect(config.standard).toBeDefined();
      expect(config.standard.red).toBe('31');
      expect(config.standard.green).toBe('32');
    });

    it('has bright colors section', () => {
      const config = loadConfig();
      expect(config.bright).toBeDefined();
      expect(config.bright.red).toBe('91');
      expect(config.bright.green).toBe('92');
    });

    it('has 256-color palette', () => {
      const config = loadConfig();
      expect(config.palette256).toBeDefined();
      expect(config.palette256.mintGreen).toBeDefined();
      expect(config.palette256.mintGreen.code).toBe('38;5;158');
    });

    it('has semantic aliases', () => {
      const config = loadConfig();
      expect(config.semantic).toBeDefined();
      expect(config.semantic.success).toBe('green');
      expect(config.semantic.error).toBe('red');
    });

    it('has high-contrast colors', () => {
      const config = loadConfig();
      expect(config.highContrast).toBeDefined();
      expect(config.highContrast.red).toBe('91');
    });
  });

  describe('generateJS', () => {
    let config;
    let jsContent;

    beforeAll(() => {
      config = loadConfig();
      jsContent = generateJS(config);
    });

    it('generates valid JavaScript', () => {
      expect(jsContent).toContain("'use strict';");
      expect(jsContent).toContain('module.exports');
    });

    it('includes auto-generated header', () => {
      expect(jsContent).toContain('Auto-generated from config/colors.yaml');
      expect(jsContent).toContain('DO NOT EDIT THIS FILE DIRECTLY');
    });

    it('includes brand hex constant', () => {
      expect(jsContent).toContain("const BRAND_HEX = '#e8683a';");
    });

    it('includes modifiers object', () => {
      expect(jsContent).toContain('const modifiers = {');
      expect(jsContent).toContain("reset: '\\x1b[0m'");
      expect(jsContent).toContain("bold: '\\x1b[1m'");
    });

    it('includes standard colors object', () => {
      expect(jsContent).toContain('const standard = {');
      expect(jsContent).toContain("red: '\\x1b[31m'");
    });

    it('includes bright colors with proper naming', () => {
      expect(jsContent).toContain('const bright = {');
      expect(jsContent).toContain("brightRed: '\\x1b[91m'");
    });

    it('includes 256-color palette with comments', () => {
      expect(jsContent).toContain('const palette256 = {');
      expect(jsContent).toContain("mintGreen: '\\x1b[38;5;158m'");
      expect(jsContent).toContain('// Healthy/success states');
    });

    it('includes cStandard combined object', () => {
      expect(jsContent).toContain('const cStandard = {');
      expect(jsContent).toContain('...modifiers');
      expect(jsContent).toContain('...standard');
    });

    it('exports all necessary objects', () => {
      expect(jsContent).toContain('BRAND_HEX,');
      expect(jsContent).toContain('modifiers,');
      expect(jsContent).toContain('cStandard,');
      expect(jsContent).toContain('highContrast,');
    });
  });

  describe('generateSH', () => {
    let config;
    let shContent;

    beforeAll(() => {
      config = loadConfig();
      shContent = generateSH(config);
    });

    it('generates valid bash script', () => {
      expect(shContent).toContain('#!/bin/bash');
    });

    it('includes auto-generated header', () => {
      expect(shContent).toContain('Auto-generated from config/colors.yaml');
      expect(shContent).toContain('DO NOT EDIT THIS FILE DIRECTLY');
    });

    it('includes modifiers with uppercase names', () => {
      expect(shContent).toContain('RESET="\\033[0m"');
      expect(shContent).toContain('BOLD="\\033[1m"');
    });

    it('includes standard colors with uppercase names', () => {
      expect(shContent).toContain('RED="\\033[31m"');
      expect(shContent).toContain('GREEN="\\033[32m"');
    });

    it('includes bright variants with BRIGHT_ prefix', () => {
      expect(shContent).toContain('BRIGHT_RED="\\033[91m"');
      expect(shContent).toContain('BRIGHT_GREEN="\\033[92m"');
    });

    it('includes semantic aliases referencing standard colors', () => {
      expect(shContent).toContain('SUCCESS="$GREEN"');
      expect(shContent).toContain('ERROR="$RED"');
    });

    it('includes 256-color palette with snake_case names', () => {
      expect(shContent).toContain('MINT_GREEN="\\033[38;5;158m"');
      expect(shContent).toContain('SKY_BLUE="\\033[38;5;117m"');
    });

    it('includes brand color', () => {
      expect(shContent).toContain('BRAND="\\033[38;2;232;104;58m"');
      expect(shContent).toContain('ORANGE="$BRAND"');
    });

    it('includes background colors', () => {
      expect(shContent).toContain('BG_RED="\\033[41m"');
      expect(shContent).toContain('BG_GREEN="\\033[42m"');
    });
  });

  describe('generated files', () => {
    it('lib/colors.generated.js exists and is valid', () => {
      const filePath = path.join(__dirname, '../../lib/colors.generated.js');
      expect(fs.existsSync(filePath)).toBe(true);

      const generated = require('../../lib/colors.generated');
      expect(generated.BRAND_HEX).toBe('#e8683a');
      expect(generated.cStandard).toBeDefined();
      expect(generated.cStandard.red).toBe('\x1b[31m');
    });

    it('scripts/lib/colors.generated.sh exists', () => {
      const filePath = path.join(__dirname, '../../scripts/lib/colors.generated.sh');
      expect(fs.existsSync(filePath)).toBe(true);

      const content = fs.readFileSync(filePath, 'utf8');
      expect(content).toContain('#!/bin/bash');
      expect(content).toContain('RED=');
    });
  });
});
