/**
 * Hook manifest aggregator.
 *
 * At install time, walks every enabled plugin's `provides.hooks` array
 * and produces a single `.agileflow/hook-manifest.yaml` that the
 * orchestrator (and the 6 dispatchers) read at runtime.
 *
 * Plugin manifests declare hooks with paths relative to the plugin's
 * source directory:
 *
 *   provides:
 *     hooks:
 *       - id: babysit-clear-restore
 *         event: SessionStart
 *         script: hooks/babysit-clear-restore.js
 *         timeout: 5000
 *         skipOnError: true
 *
 * The aggregator rewrites the script path to be relative to the
 * project root (so the orchestrator can find it after install):
 *
 *   - script: .agileflow/plugins/core/hooks/babysit-clear-restore.js
 *
 * Aggregation is content-only — the loader's strict validator runs
 * afterwards when the orchestrator reads the file, so any malformed
 * plugin contribution surfaces with a clear error rather than silently
 * misbehaving.
 */
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const HEADER_COMMENT =
  '# Auto-generated by `agileflow setup` / `agileflow update`.\n' +
  '# Do not edit by hand — your changes will be overwritten on the next install.\n' +
  '# To override per-hook settings (timeout, skipOnError, enabled),\n' +
  '# use the `hooks:` map in agileflow.config.json instead.\n' +
  '#\n';

/**
 * @typedef {import('../plugins/registry.js').PluginManifest} PluginManifest
 */

/**
 * Build a single normalized hook-manifest object from the ordered set
 * of enabled plugins. Pure: no I/O.
 *
 * @param {PluginManifest[]} orderedPlugins
 * @returns {{ version: 1, hooks: Array<object> }}
 */
function buildHookManifest(orderedPlugins) {
  /** @type {Array<object>} */
  const hooks = [];
  for (const plugin of orderedPlugins) {
    const provided =
      plugin.provides && Array.isArray(plugin.provides.hooks)
        ? plugin.provides.hooks
        : [];
    for (const entry of provided) {
      if (!entry || typeof entry !== 'object') continue;
      if (typeof entry.id !== 'string' || typeof entry.script !== 'string') continue;
      const out = {
        id: entry.id,
        event: entry.event,
        script: `.agileflow/plugins/${plugin.id}/${entry.script}`,
      };
      if (entry.matcher != null) out.matcher = entry.matcher;
      if (Array.isArray(entry.runAfter)) out.runAfter = entry.runAfter;
      if (typeof entry.timeout === 'number') out.timeout = entry.timeout;
      if (typeof entry.skipOnError === 'boolean') out.skipOnError = entry.skipOnError;
      if (typeof entry.enabled === 'boolean') out.enabled = entry.enabled;
      hooks.push(out);
    }
  }
  return { version: 1, hooks };
}

/**
 * Aggregate + atomically write the hook manifest to disk. Call only
 * when the target IDE supports hooks (i.e. claude-code today).
 *
 * @param {PluginManifest[]} orderedPlugins
 * @param {string} agileflowDir - absolute path to .agileflow/
 * @returns {Promise<string>} absolute path of the written manifest
 */
async function writeAggregatedManifest(orderedPlugins, agileflowDir) {
  const manifest = buildHookManifest(orderedPlugins);
  const dest = path.join(agileflowDir, 'hook-manifest.yaml');
  const yamlText = HEADER_COMMENT + yaml.dump(manifest, { noRefs: true });

  await fs.promises.mkdir(agileflowDir, { recursive: true });
  const tmp = path.join(
    agileflowDir,
    `.hook-manifest.yaml.tmp-${process.pid}-${Math.random().toString(36).slice(2, 10)}`,
  );
  try {
    await fs.promises.writeFile(tmp, yamlText, 'utf8');
    await fs.promises.rename(tmp, dest);
  } catch (err) {
    try {
      await fs.promises.unlink(tmp);
    } catch {
      /* swallow */
    }
    throw err;
  }
  return dest;
}

/**
 * Remove the hook manifest if it exists. Used when switching to a
 * non-claude-code IDE so a stale claude-code manifest doesn't linger.
 *
 * @param {string} agileflowDir
 * @returns {Promise<boolean>} true if a file was removed
 */
async function removeAggregatedManifest(agileflowDir) {
  const dest = path.join(agileflowDir, 'hook-manifest.yaml');
  try {
    await fs.promises.unlink(dest);
    return true;
  } catch (err) {
    if (err.code === 'ENOENT') return false;
    throw err;
  }
}

module.exports = {
  buildHookManifest,
  writeAggregatedManifest,
  removeAggregatedManifest,
  HEADER_COMMENT,
};
