import fs from 'node:fs';
import path from 'node:path';
import semver from 'semver';
import {
  hashTree,
  isNotFound,
  packMembers,
  parsePack,
  parseSidecar,
  parseSkillMarkdown,
  pickVersion,
  readTree,
  SIDECAR_FILE,
  SKILL_FILE,
  summarizeTree,
  validateSkillMarkdown,
  writeFileAtomic,
  DEFAULT_SCOPE,
} from '@agileflow/core';
import type { RegistryManifest, RegistrySkill, RegistrySkillIndex, RegistryVersion, RegistryPackIndex } from './client';
import { decodeBundle, encodeBundle } from './integrity';

export interface BuildOptions {
  skillsDir: string;
  packsDir: string;
  outDir: string;
  /** Compare against disk without writing. */
  check?: boolean;
  /**
   * TypeScript module that pins every published official integrity into the
   * CLI (`packages/registry/src/official-pins.ts`). Written/checked with the
   * registry so a CLI release vouches for the registry content it shipped with.
   */
  pinsFile?: string;
  /** Package scope every skill is published under (default `@agileflow`); `@myorg` for a team registry. */
  scope?: string;
}

export interface BuildResult {
  written: string[];
  /** Files that differ from disk (check mode) or would be created. */
  outOfDate: string[];
  errors: string[];
  /** Non-fatal findings (e.g. published skills whose source was removed). */
  warnings: string[];
  skills: Array<{ name: string; version: string; integrity: string }>;
}

/** Files a skill package may contain; anything else (dotfiles, editor litter) is refused. */
const ALLOWED_TOP_LEVEL = new Set([SKILL_FILE, SIDECAR_FILE, 'LICENSE', 'LICENSE.md', 'README.md']);
const ALLOWED_DIRS = new Set(['references', 'scripts', 'assets', 'evals', 'agents']);

function json(value: unknown): string {
  return JSON.stringify(value, null, 2) + '\n';
}

async function readJsonFile<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await fs.promises.readFile(file, 'utf8')) as T;
  } catch (err) {
    if (isNotFound(err)) return null;
    throw err;
  }
}

async function listDirs(dir: string): Promise<string[]> {
  try {
    return (await fs.promises.readdir(dir, { withFileTypes: true }))
      .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
      .map((e) => e.name)
      .sort();
  } catch (err) {
    if (isNotFound(err)) return [];
    throw err;
  }
}

function packageFileProblem(rel: string): string | null {
  const parts = rel.split('/');
  if (parts.some((p) => p.startsWith('.'))) return `${rel}: hidden files are not published`;
  if (parts.length === 1) return ALLOWED_TOP_LEVEL.has(rel) ? null : `${rel}: unexpected top-level file`;
  return ALLOWED_DIRS.has(parts[0]!) ? null : `${rel}: unexpected directory (allowed: ${[...ALLOWED_DIRS].join(', ')})`;
}

function stringField(frontmatter: Record<string, unknown>, key: string): string | undefined {
  const value = frontmatter[key];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

export function renderPinsModule(manifest: RegistryManifest): string {
  const official = Object.fromEntries(
    Object.entries(manifest.packages).filter(([name]) => name.startsWith(`${DEFAULT_SCOPE}/`)),
  );
  return (
    '// Generated by `npm run registry:build` from registry/v1/manifest.json. Do not edit.\n' +
    '// Integrities of every official package version published before this CLI was built.\n' +
    `export const OFFICIAL_PINS: Record<string, Record<string, string>> = ${JSON.stringify(official, null, 2)};\n`
  );
}

/**
 * Verify that every version already in the registry is intact: its version
 * document, its bundle, and its entry in the per-skill index agree, and the
 * bundle hashes to the recorded integrity. Published history is append-only.
 */
async function verifyHistory(outDir: string, name: string, previous: RegistrySkill, errors: string[]): Promise<void> {
  for (const [version, indexMeta] of Object.entries(previous.versions)) {
    const where = `${name}@${version}`;
    const doc = await readJsonFile<RegistryVersion>(path.join(outDir, 'v1', 'skills', ...name.split('/'), `${version}.json`));
    if (!doc) {
      errors.push(`${where}: published version document is missing (published versions are immutable)`);
      continue;
    }
    if (JSON.stringify(doc) !== JSON.stringify(indexMeta)) {
      errors.push(`${where}: version document and skill index disagree`);
    }
    let bytes: Buffer;
    try {
      bytes = await fs.promises.readFile(path.join(outDir, ...doc.url.split('/')));
    } catch {
      errors.push(`${where}: published bundle ${doc.url} is missing`);
      continue;
    }
    try {
      const bundle = decodeBundle(bytes);
      if (bundle.name !== name || bundle.version !== version) errors.push(`${where}: bundle contains ${bundle.name}@${bundle.version}`);
      if (hashTree(bundle.tree) !== doc.integrity) errors.push(`${where}: bundle does not match its published integrity`);
    } catch (err) {
      errors.push(`${where}: bundle is unreadable: ${(err as Error).message}`);
    }
  }
}

/**
 * Build the static registry from `skills/` and `packs/`.
 *
 * Published versions are immutable and append-only: rebuilding with changed
 * content under an existing version is an error, every older version is
 * re-verified on each build, and versions whose source was removed stay
 * published (locked projects keep working).
 */
export async function buildRegistry(options: BuildOptions): Promise<BuildResult> {
  const result: BuildResult = { written: [], outOfDate: [], errors: [], warnings: [], skills: [] };
  const scope = options.scope ?? DEFAULT_SCOPE;
  if (!/^@[a-z0-9][a-z0-9-]*$/.test(scope)) {
    result.errors.push(`scope "${scope}" must look like @name (lowercase letters, digits, hyphens)`);
    return result;
  }
  const outputs = new Map<string, string>();
  const skillIndex: RegistrySkillIndex = { schema: 1, skills: [] };
  const previousManifest = await readJsonFile<RegistryManifest>(path.join(options.outDir, 'v1', 'manifest.json'));
  const manifest: RegistryManifest = { schema: 1, packages: {} };
  for (const [name, versions] of Object.entries(previousManifest?.packages ?? {})) {
    manifest.packages[name] = { ...versions };
  }
  const built = new Set<string>();

  for (const dirName of await listDirs(options.skillsDir)) {
    const dir = path.join(options.skillsDir, dirName);
    const files = await readTree(dir);
    const skillFile = files.find((f) => f.path === SKILL_FILE);
    const sidecarFile = files.find((f) => f.path === SIDECAR_FILE);
    if (!skillFile || !sidecarFile) {
      result.errors.push(`${dirName}: needs ${SKILL_FILE} and ${SIDECAR_FILE}`);
      continue;
    }
    const fileProblems = files.map((f) => packageFileProblem(f.path)).filter((p): p is string => !!p);
    if (fileProblems.length) {
      result.errors.push(...fileProblems.map((p) => `${dirName}: ${p}`));
      continue;
    }
    const skillText = skillFile.content.toString('utf8');
    const issues = validateSkillMarkdown(skillText, dirName).filter((i) => i.level === 'error');
    if (issues.length) {
      result.errors.push(...issues.map((i) => `${dirName}: ${i.message}`));
      continue;
    }
    let sidecar;
    try {
      sidecar = parseSidecar(sidecarFile.content.toString('utf8'));
    } catch (err) {
      result.errors.push(`${dirName}: ${(err as Error).message}`);
      continue;
    }
    const { name, version } = sidecar.package;
    if (semver.valid(version) !== version) {
      result.errors.push(`${dirName}: version "${version}" must be canonical semver (e.g. 1.2.0)`);
      continue;
    }
    if (name !== `${scope}/${dirName}`) {
      result.errors.push(`${dirName}: package name must be ${scope}/${dirName} (got ${name})`);
      continue;
    }
    built.add(name);
    const integrity = hashTree(files);
    const summary = summarizeTree(files);
    const frontmatter = parseSkillMarkdown(skillText).frontmatter;
    const bundleRel = `packages/${name}/${version}.json`;
    const versionRel = `v1/skills/${name}/${version}.json`;
    const published = manifest.packages[name]?.[version];
    const existing = await readJsonFile<RegistryVersion>(path.join(options.outDir, versionRel));
    if ((existing && existing.integrity !== integrity) || (published && published !== integrity)) {
      result.errors.push(
        `${name}@${version} is already published with different content. Bump package.version in ${dirName}/${SIDECAR_FILE}.`,
      );
      continue;
    }
    const license = stringField(frontmatter, 'license');
    const compatibility = stringField(frontmatter, 'compatibility');
    const versionMeta: RegistryVersion = existing ?? {
      name,
      version,
      integrity,
      url: bundleRel,
      metadata: {
        description: summary.description ?? '',
        activation: sidecar.activation?.mode ?? 'auto',
        files: files.length,
        references: summary.references,
        scripts: summary.scripts,
        requirements: {
          commands: sidecar.requirements?.commands ?? [],
          network: sidecar.requirements?.network ?? 'none',
        },
        ...(license ? { license } : {}),
        ...(compatibility ? { compatibility } : {}),
      },
      compatibility: { agentSkills: sidecar.compatibility?.agentSkills ?? true, bundleFormat: 1 },
    };
    if (!existing) {
      outputs.set(bundleRel, encodeBundle(name, version, files));
      outputs.set(versionRel, json(versionMeta));
    }

    const previous = await readJsonFile<RegistrySkill>(path.join(options.outDir, `v1/skills/${name}/index.json`));
    if (previous) await verifyHistory(options.outDir, name, previous, result.errors);
    for (const v of Object.keys(manifest.packages[name] ?? {})) {
      if (!previous?.versions[v] && v !== version) {
        result.errors.push(`${name}@${v} is in the registry manifest but its version was removed (published versions are immutable)`);
      }
    }
    const versions: Record<string, RegistryVersion> = { ...(previous?.versions ?? {}), [version]: versionMeta };
    const sortedVersions = Object.fromEntries(
      Object.keys(versions)
        .sort(semver.compare)
        .map((v) => [v, versions[v]!]),
    );
    const latest = pickVersion(Object.keys(sortedVersions), '*') ?? version;
    const skillDoc: RegistrySkill = {
      schema: 1,
      name,
      description: sortedVersions[latest]!.metadata.description,
      latest,
      versions: sortedVersions,
    };
    outputs.set(`v1/skills/${name}/index.json`, json(skillDoc));
    skillIndex.skills.push({
      name,
      description: skillDoc.description,
      latest,
      versions: Object.keys(sortedVersions),
    });
    manifest.packages[name] = Object.fromEntries(
      Object.entries({ ...(manifest.packages[name] ?? {}), ...Object.fromEntries(Object.entries(sortedVersions).map(([v, m]) => [v, m.integrity])) }).sort(
        ([a], [b]) => semver.compare(a, b),
      ),
    );
    result.skills.push({ name, version, integrity });
  }

  // Published skills whose source directory was removed stay resolvable for
  // locked projects but are no longer listed.
  for (const name of Object.keys(manifest.packages)) {
    if (built.has(name)) continue;
    const previous = await readJsonFile<RegistrySkill>(path.join(options.outDir, `v1/skills/${name}/index.json`));
    if (!previous) {
      result.errors.push(`${name}: listed in the registry manifest but its index is missing (published versions are immutable)`);
      continue;
    }
    await verifyHistory(options.outDir, name, previous, result.errors);
    result.warnings.push(`${name}: no longer in skills/; published versions stay available but unlisted`);
  }
  outputs.set('v1/skills/index.json', json(skillIndex));
  manifest.packages = Object.fromEntries(Object.entries(manifest.packages).sort(([a], [b]) => (a < b ? -1 : 1)));

  const packIndex: RegistryPackIndex = { schema: 1, packs: [] };
  let packFiles: string[] = [];
  try {
    packFiles = (await fs.promises.readdir(options.packsDir)).filter((f) => /\.ya?ml$/.test(f)).sort();
  } catch (err) {
    if (!isNotFound(err)) throw err;
  }
  const packNames = new Map<string, string>();
  for (const file of packFiles) {
    try {
      const pack = parsePack(await fs.promises.readFile(path.join(options.packsDir, file), 'utf8'), file);
      const fullName = pack.name.startsWith('@') ? pack.name : `${scope}/${pack.name}`;
      const clash = packNames.get(fullName);
      if (clash) throw new Error(`pack name ${fullName} is also used by ${clash}`);
      packNames.set(fullName, file);
      const seen = new Set<string>();
      for (const member of packMembers(pack)) {
        if (seen.has(member.id)) throw new Error(`lists ${member.source} more than once`);
        seen.add(member.id);
        const known = skillIndex.skills.find((s) => s.name === member.source);
        if (!known) throw new Error(`references unknown skill ${member.source}`);
        if (!pickVersion(known.versions, member.range)) {
          throw new Error(`no published version of ${member.source} satisfies ${member.range}`);
        }
      }
      outputs.set(`v1/packs/${fullName}.json`, json({ ...pack, name: fullName }));
      packIndex.packs.push({ name: fullName, description: pack.description, version: pack.version });
    } catch (err) {
      result.errors.push(`pack ${file}: ${(err as Error).message}`);
    }
  }
  outputs.set('v1/packs/index.json', json(packIndex));
  outputs.set('v1/manifest.json', json(manifest));

  if (result.errors.length) return result;

  // Bundles and version documents first, indexes and the manifest last, so an
  // interrupted build never publishes an index that points at a missing file.
  const order = (rel: string) => (rel.startsWith('packages/') ? 0 : /\/\d[^/]*\.json$/.test(rel) ? 1 : 2);
  const entries = [...outputs.entries()].sort(([a], [b]) => order(a) - order(b) || (a < b ? -1 : 1));
  const targets: Array<[string, string, string]> = entries.map(([rel, content]) => [rel, path.join(options.outDir, ...rel.split('/')), content]);
  if (options.pinsFile) targets.push(['(pins) ' + path.basename(options.pinsFile), options.pinsFile, renderPinsModule(manifest)]);
  for (const [rel, abs, content] of targets) {
    let current: string | null = null;
    try {
      current = await fs.promises.readFile(abs, 'utf8');
    } catch (err) {
      if (!isNotFound(err)) throw err;
    }
    if (current === content) continue;
    result.outOfDate.push(rel);
    if (!options.check) {
      await writeFileAtomic(abs, content);
      result.written.push(rel);
    }
  }
  return result;
}
