/**
 * Skill learnings — persistent self-improvement signals per skill.
 *
 * Learnings live inside the installed skill directory so they are
 * co-located with the skill that owns them:
 *   <skillsDir>/<skillName>/_learnings/<skill>.yaml
 *
 * File format:
 *   # Auto-generated by AgileFlow. Edit carefully — these shape skill behavior.
 *   version: 1
 *   skill: agileflow-research
 *   updated: "2026-05-06"
 *   entries:
 *     - id: "abc123"
 *       confidence: high     # high / medium / low
 *       created: "2026-05-06"
 *       observation: "User prefers concise research prompts..."
 *       source: correction   # correction | confirmation | observation
 *
 * Confidence levels:
 *   - high:   explicit user correction
 *   - medium: pattern accepted without correction
 *   - low:    observation; not yet confirmed
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const yaml = require("js-yaml");

const VALID_CONFIDENCE = new Set(["high", "medium", "low"]);
const VALID_SOURCE = new Set(["correction", "confirmation", "observation"]);
const CONFIDENCE_ORDER = { high: 0, medium: 1, low: 2 };

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Resolve the skillsDir for the primary IDE target from agileflow.config.json.
 * Falls back to `.claude/skills` if config is absent or unreadable.
 *
 * @param {string} projectDir
 * @returns {string} absolute path to the skills directory
 */
function resolveSkillsDir(projectDir) {
  let IDE_CAPABILITIES = null;
  try {
    ({ IDE_CAPABILITIES } = require("../ide/capabilities.js"));
  } catch {
    // unavailable — use default
  }

  let cfg = {};
  try {
    const raw = fs.readFileSync(
      path.join(projectDir, "agileflow.config.json"),
      "utf8",
    );
    cfg = JSON.parse(raw);
  } catch {
    // config absent — use default
  }

  const primaryIde =
    Array.isArray(cfg?.ide?.targets) && cfg.ide.targets.length > 0
      ? cfg.ide.targets[0]
      : "claude-code";

  const skillsDir =
    IDE_CAPABILITIES?.[primaryIde]?.skillsDir ?? ".claude/skills";
  return path.join(projectDir, skillsDir);
}

/**
 * Resolve the absolute path of a learnings file for a given skill.
 * The `learns.file` field from frontmatter (e.g. `_learnings/research.yaml`)
 * is resolved relative to the skill's installed directory.
 *
 * @param {string} skillsDir - absolute path to the IDE skills dir
 * @param {string} skillName - e.g. "agileflow-research"
 * @param {string} [learnFile] - relative path from frontmatter, e.g. "_learnings/research.yaml"
 * @returns {string}
 */
function resolveLearnFile(skillsDir, skillName, learnFile) {
  const file = learnFile || `_learnings/${skillName}.yaml`;
  // Prevent path traversal: discard any leading ../ segments.
  const safeParts = file.split("/").filter((p) => p && p !== ".." && p !== ".");
  return path.join(skillsDir, skillName, ...safeParts);
}

// ---------------------------------------------------------------------------
// Public API (new spec)
// ---------------------------------------------------------------------------

/**
 * Read learnings for a skill.
 *
 * @param {string} skillName
 * @param {string} [projectDir]
 * @returns {Promise<{ entries: Array, version: number, skill: string }>}
 */
async function readLearnings(skillName, projectDir) {
  const dir = projectDir || process.env.AGILEFLOW_PROJECT_DIR || process.cwd();
  const skillsDir = resolveSkillsDir(dir);
  // Look for the standard learnings file path.
  const p = resolveLearnFile(skillsDir, skillName);

  let text;
  try {
    text = await fs.promises.readFile(p, "utf8");
  } catch (err) {
    if (err.code === "ENOENT")
      return { entries: [], version: 1, skill: skillName };
    throw err;
  }
  if (!text.trim()) return { entries: [], version: 1, skill: skillName };

  let doc;
  try {
    doc = yaml.load(text);
  } catch (err) {
    throw new Error(`learnings file ${p} is not valid YAML: ${err.message}`);
  }
  if (!doc || typeof doc !== "object" || !Array.isArray(doc.entries)) {
    return { entries: [], version: 1, skill: skillName };
  }
  return {
    entries: doc.entries,
    version: doc.version ?? 1,
    skill: doc.skill ?? skillName,
  };
}

/**
 * Append a new learning entry.
 *
 * @param {string} skillName
 * @param {string} projectDir
 * @param {{ observation: string, confidence?: string, source?: string }} entry
 * @param {{ maxEntries?: number, learnFile?: string }} [opts]
 * @returns {Promise<void>}
 */
async function appendLearning(skillName, projectDir, entry, opts = {}) {
  const { observation, confidence = "medium", source = "observation" } = entry;
  const { maxEntries = 30, learnFile } = opts;

  if (typeof observation !== "string" || !observation.trim()) {
    throw new Error("observation must be a non-empty string");
  }
  if (!VALID_CONFIDENCE.has(confidence)) {
    throw new Error(
      `confidence must be one of ${[...VALID_CONFIDENCE].join(", ")}`,
    );
  }
  if (!VALID_SOURCE.has(source)) {
    throw new Error(`source must be one of ${[...VALID_SOURCE].join(", ")}`);
  }
  if (!Number.isInteger(maxEntries) || maxEntries <= 0) {
    throw new Error("maxEntries must be a positive integer");
  }

  const dir = projectDir || process.env.AGILEFLOW_PROJECT_DIR || process.cwd();
  const skillsDir = resolveSkillsDir(dir);
  const p = resolveLearnFile(skillsDir, skillName, learnFile);

  // Ensure directory exists.
  await fs.promises.mkdir(path.dirname(p), { recursive: true });

  // Read existing entries (tolerate missing file).
  let existing = { entries: [], version: 1, skill: skillName };
  try {
    const text = await fs.promises.readFile(p, "utf8");
    if (text.trim()) {
      const doc = yaml.load(text);
      if (doc && Array.isArray(doc.entries)) {
        existing = {
          entries: doc.entries,
          version: doc.version ?? 1,
          skill: doc.skill ?? skillName,
        };
      }
    }
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }

  const id = crypto.randomBytes(3).toString("hex");
  const created = new Date().toISOString().slice(0, 10);

  existing.entries.push({
    id,
    confidence,
    created,
    observation: observation.trim(),
    source,
  });

  // Trim oldest entries if over cap.
  if (existing.entries.length > maxEntries) {
    existing.entries.splice(0, existing.entries.length - maxEntries);
  }

  const header = `# Auto-generated by AgileFlow. Edit carefully — these shape skill behavior.\n`;
  const doc = {
    version: existing.version,
    skill: skillName,
    updated: created,
    entries: existing.entries,
  };
  const body = yaml.dump(doc, { lineWidth: 120 });

  // Atomic write via temp file + rename.
  const tmp = `${p}.tmp-${process.pid}`;
  await fs.promises.writeFile(tmp, header + body, "utf8");
  await fs.promises.rename(tmp, p);
}

/**
 * Format learnings as a markdown block for injection into context.
 * Returns null if there are no entries.
 * Sorts entries by confidence: high first, then medium, then low.
 *
 * @param {{ entries: Array<{confidence: string, observation: string}>, skill?: string }} learnings
 * @returns {string|null}
 */
function formatLearningsBlock(learnings) {
  if (
    !learnings ||
    !Array.isArray(learnings.entries) ||
    learnings.entries.length === 0
  ) {
    return null;
  }

  const sorted = [...learnings.entries].sort(
    (a, b) =>
      (CONFIDENCE_ORDER[a.confidence] ?? 99) -
      (CONFIDENCE_ORDER[b.confidence] ?? 99),
  );

  const skillLabel = learnings.skill || "skill";
  const lines = [
    `## Learned preferences (${skillLabel})`,
    "",
    "From past sessions in this project:",
  ];

  for (const e of sorted) {
    lines.push(`- [${e.confidence} confidence] ${e.observation}`);
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Legacy API (kept for install.js compat)
// ---------------------------------------------------------------------------

const LEARNINGS_DIR_REL = path.join(".agileflow", "skills", "_learnings");

/**
 * Resolve path for legacy scaffold usage.
 * @param {string} projectRoot
 * @param {string} file
 */
function learningsPath(projectRoot, file) {
  const flat = path.basename(file || "").trim();
  if (!flat || flat.startsWith(".")) {
    throw new Error(`invalid learnings filename: ${JSON.stringify(file)}`);
  }
  return path.join(projectRoot, LEARNINGS_DIR_REL, flat);
}

/**
 * Create an empty learnings file in the legacy location if it does not exist.
 * Used by install.js to scaffold at install time.
 *
 * @param {string} projectRoot
 * @param {string} skillId
 * @param {string} file
 * @returns {Promise<{ path: string, created: boolean }>}
 */
async function scaffoldLearnings(projectRoot, skillId, file) {
  const p = learningsPath(projectRoot, file);
  await fs.promises.mkdir(path.dirname(p), { recursive: true });
  try {
    await fs.promises.access(p);
    return { path: p, created: false };
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }
  const header = `# AgileFlow skill learnings — ${skillId}\n# Append-only signals; oldest trimmed when count exceeds maxEntries.\nentries: []\n`;
  await fs.promises.writeFile(p, header, "utf8");
  return { path: p, created: true };
}

module.exports = {
  // New spec API
  readLearnings,
  appendLearning,
  formatLearningsBlock,
  resolveSkillsDir,
  resolveLearnFile,
  // Legacy (install.js compat)
  scaffoldLearnings,
  learningsPath,
  LEARNINGS_DIR_REL,
};
