#!/usr/bin/env node

/**
 * generate-colors.js - Generate color files from YAML config
 *
 * Reads config/colors.yaml and generates:
 *   - lib/colors.js (JavaScript module)
 *   - scripts/lib/colors.sh (Bash script)
 *
 * Usage:
 *   node scripts/generate-colors.js
 *   node scripts/generate-colors.js --check  # Verify files are up-to-date
 *
 * This ensures a single source of truth for all color definitions.
 */

const fs = require('fs');
const path = require('path');
const { safeLoad } = require('../lib/yaml-utils');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(ROOT, 'config', 'colors.yaml');
const JS_OUTPUT = path.join(ROOT, 'lib', 'colors.generated.js');
const SH_OUTPUT = path.join(ROOT, 'scripts', 'lib', 'colors.generated.sh');

/**
 * Load colors configuration from YAML
 * @returns {Object} Colors configuration
 */
function loadConfig() {
  const content = fs.readFileSync(CONFIG_PATH, 'utf8');
  return safeLoad(content);
}

/**
 * Generate JavaScript module content
 * @param {Object} config - Colors configuration
 * @returns {string} JavaScript module content
 */
function generateJS(config) {
  const lines = [
    '/**',
    ' * colors.generated.js - Auto-generated from config/colors.yaml',
    ' *',
    ' * DO NOT EDIT THIS FILE DIRECTLY.',
    ' * Run: node scripts/generate-colors.js',
    ' *',
    ` * Generated: ${new Date().toISOString()}`,
    ' */',
    '',
    "'use strict';",
    '',
  ];

  // Brand color
  lines.push(`// Brand color`);
  lines.push(`const BRAND_HEX = '${config.brand.hex}';`);
  lines.push('');

  // Modifiers
  lines.push('// Modifiers');
  lines.push('const modifiers = {');
  for (const [name, code] of Object.entries(config.modifiers)) {
    lines.push(`  ${name}: '\\x1b[${code}m',`);
  }
  lines.push('};');
  lines.push('');

  // Standard colors
  lines.push('// Standard ANSI colors');
  lines.push('const standard = {');
  for (const [name, code] of Object.entries(config.standard)) {
    lines.push(`  ${name}: '\\x1b[${code}m',`);
  }
  lines.push('};');
  lines.push('');

  // Bright colors
  lines.push('// Bright ANSI colors');
  lines.push('const bright = {');
  for (const [name, code] of Object.entries(config.bright)) {
    lines.push(`  bright${name.charAt(0).toUpperCase() + name.slice(1)}: '\\x1b[${code}m',`);
  }
  lines.push('};');
  lines.push('');

  // 256-color palette
  lines.push('// 256-color palette');
  lines.push('const palette256 = {');
  for (const [name, def] of Object.entries(config.palette256)) {
    const comment = def.comment ? ` // ${def.comment}` : '';
    lines.push(`  ${name}: '\\x1b[${def.code}m',${comment}`);
  }
  lines.push('};');
  lines.push('');

  // Background colors
  lines.push('// Background colors');
  lines.push('const backgrounds = {');
  for (const [name, code] of Object.entries(config.backgrounds)) {
    lines.push(`  bg${name.charAt(0).toUpperCase() + name.slice(1)}: '\\x1b[${code}m',`);
  }
  lines.push('};');
  lines.push('');

  // Brand color ANSI
  lines.push('// Brand color ANSI');
  lines.push(`const brand = '\\x1b[${config.brand.ansi}m';`);
  lines.push('');

  // High contrast colors
  lines.push('// High-contrast mode colors (WCAG AAA)');
  lines.push('const highContrast = {');
  for (const [name, code] of Object.entries(config.highContrast)) {
    lines.push(`  ${name}: '\\x1b[${code}m',`);
  }
  lines.push('};');
  lines.push('');

  // Combined cStandard object (for backward compatibility)
  lines.push('// Combined standard color palette');
  lines.push('const cStandard = {');
  lines.push('  ...modifiers,');
  lines.push('  ...standard,');
  lines.push('  ...bright,');
  lines.push('  ...palette256,');
  lines.push('  ...backgrounds,');
  lines.push('  brand,');
  lines.push(`  orange: brand, // Alias`);
  lines.push('  // Semantic aliases');
  for (const [semantic, target] of Object.entries(config.semantic)) {
    lines.push(`  ${semantic}: standard.${target},`);
  }
  lines.push('};');
  lines.push('');

  // Exports
  lines.push('module.exports = {');
  lines.push('  BRAND_HEX,');
  lines.push('  modifiers,');
  lines.push('  standard,');
  lines.push('  bright,');
  lines.push('  palette256,');
  lines.push('  backgrounds,');
  lines.push('  brand,');
  lines.push('  highContrast,');
  lines.push('  cStandard,');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate Bash script content
 * @param {Object} config - Colors configuration
 * @returns {string} Bash script content
 */
function generateSH(config) {
  const lines = [
    '#!/bin/bash',
    '# colors.generated.sh - Auto-generated from config/colors.yaml',
    '#',
    '# DO NOT EDIT THIS FILE DIRECTLY.',
    '# Run: node scripts/generate-colors.js',
    '#',
    `# Generated: ${new Date().toISOString()}`,
    '#',
    '# Usage: source "$(dirname "${BASH_SOURCE[0]}")/colors.generated.sh"',
    '',
    '# ============================================================================',
    '# Modifiers',
    '# ============================================================================',
  ];

  for (const [name, code] of Object.entries(config.modifiers)) {
    lines.push(`${name.toUpperCase()}="\\033[${code}m"`);
  }
  lines.push('');

  lines.push('# ============================================================================');
  lines.push('# Standard ANSI Colors');
  lines.push('# ============================================================================');
  for (const [name, code] of Object.entries(config.standard)) {
    lines.push(`${name.toUpperCase()}="\\033[${code}m"`);
  }
  lines.push('');

  lines.push('# ============================================================================');
  lines.push('# Bright Variants');
  lines.push('# ============================================================================');
  for (const [name, code] of Object.entries(config.bright)) {
    lines.push(`BRIGHT_${name.toUpperCase()}="\\033[${code}m"`);
  }
  lines.push('');

  lines.push('# ============================================================================');
  lines.push('# Semantic Aliases');
  lines.push('# ============================================================================');
  for (const [semantic, target] of Object.entries(config.semantic)) {
    lines.push(`${semantic.toUpperCase()}="$${target.toUpperCase()}"`);
  }
  lines.push('');

  lines.push('# ============================================================================');
  lines.push('# 256-Color Palette');
  lines.push('# ============================================================================');
  for (const [name, def] of Object.entries(config.palette256)) {
    const varName = name.replace(/([A-Z])/g, '_$1').toUpperCase();
    const comment = def.comment ? `  # ${def.comment}` : '';
    lines.push(`${varName}="\\033[${def.code}m"${comment}`);
  }
  lines.push('');

  lines.push('# ============================================================================');
  lines.push('# Brand Color');
  lines.push('# ============================================================================');
  lines.push(`BRAND="\\033[${config.brand.ansi}m"`);
  lines.push('ORANGE="$BRAND"  # Alias');
  lines.push('');

  lines.push('# ============================================================================');
  lines.push('# Background Colors');
  lines.push('# ============================================================================');
  for (const [name, code] of Object.entries(config.backgrounds)) {
    lines.push(`BG_${name.toUpperCase()}="\\033[${code}m"`);
  }
  lines.push('');

  return lines.join('\n');
}

/**
 * Main function
 */
function main() {
  const checkMode = process.argv.includes('--check');

  console.log('🎨 Color Generator');
  console.log('==================');
  console.log(`Config: ${CONFIG_PATH}`);

  // Load configuration
  const config = loadConfig();
  console.log('✓ Loaded colors.yaml');

  // Generate content
  const jsContent = generateJS(config);
  const shContent = generateSH(config);

  if (checkMode) {
    // Check if files are up-to-date
    let upToDate = true;

    try {
      const existingJS = fs.readFileSync(JS_OUTPUT, 'utf8');
      // Compare without timestamp line
      const normalizeJS = content =>
        content
          .split('\n')
          .filter(line => !line.includes('Generated:'))
          .join('\n');
      if (normalizeJS(existingJS) !== normalizeJS(jsContent)) {
        console.log('✗ lib/colors.generated.js is out of date');
        upToDate = false;
      } else {
        console.log('✓ lib/colors.generated.js is up to date');
      }
    } catch {
      console.log('✗ lib/colors.generated.js does not exist');
      upToDate = false;
    }

    try {
      const existingSH = fs.readFileSync(SH_OUTPUT, 'utf8');
      const normalizeSH = content =>
        content
          .split('\n')
          .filter(line => !line.includes('Generated:'))
          .join('\n');
      if (normalizeSH(existingSH) !== normalizeSH(shContent)) {
        console.log('✗ scripts/lib/colors.generated.sh is out of date');
        upToDate = false;
      } else {
        console.log('✓ scripts/lib/colors.generated.sh is up to date');
      }
    } catch {
      console.log('✗ scripts/lib/colors.generated.sh does not exist');
      upToDate = false;
    }

    if (!upToDate) {
      console.log('\nRun: node scripts/generate-colors.js');
      process.exit(1);
    }
    console.log('\n✓ All color files are up to date');
    return;
  }

  // Write files
  fs.writeFileSync(JS_OUTPUT, jsContent);
  console.log(`✓ Generated ${JS_OUTPUT}`);

  fs.writeFileSync(SH_OUTPUT, shContent);
  console.log(`✓ Generated ${SH_OUTPUT}`);

  console.log('\n✓ Color generation complete!');
}

if (require.main === module) {
  main();
}

module.exports = { loadConfig, generateJS, generateSH };
