#!/bin/bash
# colors.generated.sh - Auto-generated from config/colors.yaml
#
# DO NOT EDIT THIS FILE DIRECTLY.
# Run: node scripts/generate-colors.js
#
# Generated: 2026-01-29T08:28:33.726Z
#
# Usage: source "$(dirname "${BASH_SOURCE[0]}")/colors.generated.sh"

# ============================================================================
# Modifiers
# ============================================================================
RESET="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
ITALIC="\033[3m"
UNDERLINE="\033[4m"

# ============================================================================
# Standard ANSI Colors
# ============================================================================
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
BLACK="\033[30m"

# ============================================================================
# Bright Variants
# ============================================================================
BRIGHT_RED="\033[91m"
BRIGHT_GREEN="\033[92m"
BRIGHT_YELLOW="\033[93m"
BRIGHT_BLUE="\033[94m"
BRIGHT_MAGENTA="\033[95m"
BRIGHT_CYAN="\033[96m"
BRIGHT_WHITE="\033[97m"
BRIGHT_BLACK="\033[90m"

# ============================================================================
# Semantic Aliases
# ============================================================================
SUCCESS="$GREEN"
ERROR="$RED"
WARNING="$YELLOW"
INFO="$CYAN"

# ============================================================================
# 256-Color Palette
# ============================================================================
MINT_GREEN="\033[38;5;158m"  # Healthy/success states
PEACH="\033[38;5;215m"  # Warning states
CORAL="\033[38;5;203m"  # Critical/error states
LIGHT_GREEN="\033[38;5;194m"  # Session healthy
LIGHT_YELLOW="\033[38;5;228m"  # Session warning
LIGHT_PINK="\033[38;5;210m"  # Session critical
SKY_BLUE="\033[38;5;117m"  # Directories/paths, ready states
LAVENDER="\033[38;5;147m"  # Model info, story IDs
SOFT_GOLD="\033[38;5;222m"  # Cost/money
TEAL="\033[38;5;80m"  # Pending states
SLATE="\033[38;5;103m"  # Secondary info
ROSE="\033[38;5;211m"  # Blocked/critical accent
AMBER="\033[38;5;214m"  # WIP/in-progress accent
POWDER="\033[38;5;153m"  # Labels/headers

# ============================================================================
# Brand Color
# ============================================================================
BRAND="\033[38;2;232;104;58m"
ORANGE="$BRAND"  # Alias

# ============================================================================
# Background Colors
# ============================================================================
BG_RED="\033[41m"
BG_GREEN="\033[42m"
BG_YELLOW="\033[43m"
BG_BLUE="\033[44m"
